### PR TITLE
Assignment

### PR DESCRIPTION
**Pull request by Urooj1607**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Completed the  assignment tasks
## What did you learn from the changes you have made?
l learned to create new directories, new files and moving directories and files.
## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
At this moment, this was the best approach for me.
## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
Cloning of repository was challenging.
## How were these changes tested?
Testing them on the terminal.
## A reference to a related issue in your repository (if applicable)
NA
## Checklist
- [x] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by pedram-aliniaye-asli** [comment]
You did a good job here!
A few things to notice:
1) In this part:

`cp /*server*.log ./data/raw ./data/processed/server_logs`

You seem to be copying files from the root directory (/) instead of the ./data/raw folder. Instead, you should be targeting the ./data/raw directory like this:

`cp ./data/raw/*server*.log ./data/processed/server_logs/`

Repeat this adjustment for the other copy commands:

```
cp ./data/raw/*user*.log ./data/processed/user_logs/
cp ./data/raw/*event*.log ./data/processed/event_logs/
```
2) For the rm command, there are a few problems:

    The *ipaddr pattern needs to be specified more precisely to avoid errors.
    The rf part should be corrected. The command `rm *ipaddr ./data/raw ./data/processed/user_logsrf -rf ./data` is malformed.

You should remove files containing ipaddr with the following:

```
rm ./data/raw/*ipaddr*
rm ./data/processed/user_logs/*ipaddr*
```

3) Your last command is trying to copy files directly into inventory.txt, but that won’t work as expected. You should list the files and append them to inventory.txt.
Please go ahead and do the modifications and then let me know. Thanks!

**Review by anjali-deshpande-hub — CHANGES_REQUESTED** [review]
Question 6 and 7: There are typos in line nos. 37 and 39

**Review by anjali-deshpande-hub — CHANGES_REQUESTED** [review]
Question 4: You would have to create processed dir before making sub directories inside it OR create dirs recursively using another option with mkdir command.

**Comment by pedram-aliniaye-asli** [comment]
you did a great job here!
I checked your `assignment.sh` file.
Please go ahead and close this pull request now. Thanks!

**Pull request closed without merging**
